-- Create contact_info table
CREATE TABLE IF NOT EXISTS contact_info (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  address TEXT NOT NULL,
  phone VARCHAR(100) NOT NULL,
  email VARCHAR(191) NOT NULL,
  hours_weekdays VARCHAR(191) NOT NULL,
  hours_weekends VARCHAR(191) NOT NULL,
  map_embed TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
